-- The campaign book's rules text, served only to signed-in players and only
-- for entries their own arsenal actually holds.
--
-- WHY THIS TABLE EXISTS, AND WHAT IT IS NOT
--
-- CLAUDE.md §4 says rules text is never persisted — "not to a localStorage key,
-- not to the JSON export, not to D1". This is the second explicit amendment by
-- owner decision, after v0.5.0's display-only exception, and it is narrower
-- than it looks:
--
--   * There is NO public read. `/api/book` requires a session.
--   * There is NO write endpoint. Rows are loaded by hand with
--     `wrangler d1 execute --file`, from SQL generated by
--     `scripts/book-to-sql.mjs` off the owner's own local copy. A table with no
--     write surface cannot be tampered with through the app.
--   * A caller can only ever read text for entries **their own arsenals
--     hold**. To collect the book you would have to earn every advancement and
--     buy every item, across many real campaign weeks. That is the property
--     that makes this worth doing rather than serving a JSON file.
--
-- The keys match `src/lib/book.js` exactly — `advancement:<table>:<value>:<name>`,
-- `equipment:<id>`, `injury:<id>` — so the client asks for what it already
-- knows how to name, and the server decides what it is allowed to answer.
--
-- Deliberately no `owner_user_id`: this is one shared reference table, not
-- per-player data. Every other table in this schema is scoped by owner and this
-- one is not, which is exactly why the entitlement lives in `bookStore.js`
-- instead of in a WHERE clause on this table. Read that file's header before
-- changing anything here.

CREATE TABLE IF NOT EXISTS book_text (
  key        TEXT PRIMARY KEY,
  text       TEXT NOT NULL,
  updated_at INTEGER NOT NULL
);
