#!/usr/bin/env node
/**
 * Turn your local `public/book.json` into SQL for the `book_text` table.
 *
 *   node scripts/book-to-sql.mjs > book.sql
 *   npx wrangler d1 execute hodgepodge-hearthside --remote --file=./book.sql
 *   rm book.sql
 *
 * **There is deliberately no write endpoint.** Loading by hand means the table
 * has no write surface reachable from the app, so nothing an attacker can send
 * can change or add to it. It also means this is a thing you do on purpose,
 * with the book open, rather than something a UI does quietly.
 *
 * `d1 execute --file` is atomic — a file whose last statement fails rolls the
 * whole thing back — so a half-loaded book is not a state that can happen.
 *
 * Output goes to stdout, never to a file in the repo, and `book.sql` is
 * gitignored anyway. Delete it when you are done: it is the book in the clear.
 *
 * Only filled entries are emitted. Running it against the empty scaffold
 * produces nothing but a comment, which is the correct no-op.
 */

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const source = path.join(root, 'public', 'book.json')

if (!fs.existsSync(source)) {
  console.error('No public/book.json. Run `npm run book` to write the scaffold first.')
  process.exit(1)
}

let book
try {
  book = JSON.parse(fs.readFileSync(source, 'utf8'))
} catch {
  console.error('public/book.json is not valid JSON.')
  process.exit(1)
}

const rows = Object.entries(book)
  .filter(([key, value]) => !key.endsWith('::page') && typeof value === 'string' && value.trim())

if (rows.length === 0) {
  console.log('-- Nothing to load: public/book.json has no filled entries.')
  process.exit(0)
}

/** SQLite string literal: double the single quotes and nothing else. */
const q = (s) => `'${String(s).replace(/'/g, "''")}'`

const now = Date.now()
const lines = [
  '-- Generated by scripts/book-to-sql.mjs. Do not commit this file.',
  `-- ${rows.length} entries.`,
  '',
]

for (const [key, text] of rows) {
  lines.push(
    `INSERT INTO book_text (key, text, updated_at) VALUES (${q(key)}, ${q(text)}, ${now})`
    + '  ON CONFLICT(key) DO UPDATE SET text = excluded.text, updated_at = excluded.updated_at;'
  )
}

console.log(lines.join('\n'))
